// This file is generated by build:assets script. Changes will be overridden.

export enum ASSET_NAMES {
"analysis" = "analysis",
"analytics" = "analytics",
"newspaper" = "newspaper",
"report" = "report",
};
