ASSETS=$(find ./public/assets/symbols/ -type f -name '*.svg' | sed -e 's/^\.\/src\/icons\///' | sed -e 's/.*\///' | sed -e 's/\.svg//' | sort | uniq)
PATH=src/components/Asset/Asset.types.ts

echo '// This file is generated by build:assets script. Changes will be overridden.

export enum ASSET_NAMES {' >$PATH

for asset in $ASSETS
do
  echo "  \"$asset\" = \"$asset\"," >>$PATH
done

echo '}' >>$PATH

