ICONS=$(find ./src/assets/icons -type f -name '*.svg' | sed -e 's/^\.\/src\/icons\///' | sed -e 's/.*\///' | sed -e 's/\.svg//' | sort | uniq)
PATH=src/components/Icon/Icon.types.ts

echo '// This file is generated by build:icons script. Changes will be overridden.

export enum ICON_NAMES {' >$PATH

for icons in $ICONS
do
  echo "  \"$icons\" = \"$icons\"," >>$PATH
done

echo '}' >>$PATH

