ASSETS=$(find ./public/assets/symbols/ -type f -name '*.svg' | sed -e 's/^\.\/src\/icons\///' | sed -e 's/.*\///' | sed -e 's/\.svg//' | sort | uniq)
PATH=src/components/Asset/_internals/constants.js

echo '// This file is generated by build:assets script. Changes will be overridden.

export const ASSETS = [' >$PATH

for asset in $ASSETS
do
  echo "\"$asset\"," >>$PATH
done

echo '];' >>$PATH

