name: Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run build
        run: yarn build
        env:
          SKIP_PREFLIGHT_CHECK: true
